### ISSUE TITLE
checklist: workshop website

### ISSUE THREAD

**Issue by nehamoopen** [nehamoopen/workshop-worcs-pilot#1]
- [x] badge linking to GitHub Pages
- [x] workshop blurb
- [x] installation instructions (link to Caspar's vignette)
- [x] schedule
- [x] pre-requisites (checklist: own project vs. demo project)
- [x] course materials (table with links to the WORCS phases/step-by-step instructions + notes) 
- [x] references & external resources
- [x] acknowledgements 
- [x] add license to repo
- [x] host data files + add links in text
- [x] add slides to additional materials
- [x] add Caspar to acknowlegments with link to https://cjvanlissa.github.io/worcs/index.html

**Comment by nehamoopen** [comment]
All done! I also added some extra resources, in case they turn out to be useful.
