### ISSUE TITLE
checklist: future workshops

### ISSUE THREAD

**Issue by bmkramer** [nehamoopen/workshop-worcs-pilot#2]
- [ ] provide participants with handout / checklist / issue template (if such a thing exists) of the phases + steps
- [ ] an introduction video
- [ ] an introductory presentation
- [ ] a tutorial video
- [ ] a presentation of the phases / steps
- [ ] bookdown upgrade
- [ ] adapt workshop program based on feedback
- [ ] demo project (data, code, text, references) for those without their own research projects
- [ ] alternative instructions for those without access to Git (e.g. participants from UMCU)
